config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :faqs
  resources :agents
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer, :index, :category)
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_faq.html.erb
    <div class="row">
        <div class="col-lg-12">
            <div class="panel-group" id="accordion">
              <% Faq.all.each do |faq| %>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=faq.id%>"><%=faq.question%></a>
                        </h4>
                    </div>
                    <div id="collapse<%=faq.id%>" class="panel-collapse collapse">
                        <div class="panel-body">
                            <%=faq.answer%>
                        </div>
                    </div>
                </div>
              <% end %>
            </div>
            <!-- /.panel-group -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

app/views/faqs/_form.html.slim
= simple_form_for(@faq) do |f|
  = f.error_notification

  .form-inputs
    = f.input :question
    = f.input :answer
    = f.input :index
    = f.input :category

  .form-actions
    = f.button :submit

app/views/faqs/edit.html.slim
h1 Editing faq

== render 'form'

= link_to 'Show', @faq
'|
= link_to 'Back', faqs_path

app/views/faqs/index.html.slim
h1 Listing faqs

table
  thead
    tr
      th Question
      th Answer
      th Index
      th Category
      th
      th
      th

  tbody
    - @faqs.each do |faq|
      tr
        td = faq.question
        td = faq.answer
        td = faq.index
        td = faq.category
        td = link_to 'Show', faq
        td = link_to 'Edit', edit_faq_path(faq)
        td = link_to 'Destroy', faq, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Faq', new_faq_path

app/views/faqs/new.html.slim
h1 New faq

== render 'form'

= link_to 'Back', faqs_path

app/views/faqs/show.html.slim
p#notice = notice

p
  strong Question:
  = @faq.question
p
  strong Answer:
  = @faq.answer
p
  strong Index:
  = @faq.index
p
  strong Category:
  = @faq.category

= link_to 'Edit', edit_faq_path(@faq)
'|
= link_to 'Back', faqs_path